POST http://localhost:3001/hsp/adminUsers/register
content-type: application/json

{
    "idUsuario": "10284552",
    "pass": "root",
    "nombre":"Periquito" ,
    "apellido": "piopio",
    "fechaNacimiento":"1992-10-18"
}