POST http://localhost:3001/hsp/adminUsers/register
content-type: application/json

{
    "idUsuario": "102984552",
    "pass": "1234",
    "nombre":"Periquito" ,
    "apellido": "piopio",
    "fechaNacimiento":"1992-10-18"
}